name: Container

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  check-it-out:
#    runs-on: ubuntu-latest
#    steps:
#        - name: Checkout
#          uses: actions/checkout@v2
          
  my-container-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/snowflakedb/ske/ubuntu-sc:latest
      env:
        SF_ACCOUNT: ${{ secrets.sf_account }}
        SF_USERNAME: ${{ secrets.sf_username }}
        SF_ROLE: ${{ secrets.sf_role }}
        SF_WAREHOUSE: ${{ secrets.sf_warehouse }}
        SF_DATABASE: ${{ secrets.sf_database }}
        SNOWFLAKE_PASSWORD: ${{ secrets.sf_password }}
        ENV: DEV
#      volumes:
#        - /home/runner/work/docker_test_code/docker_test_code/schemachange_delta:/github/workspace/schemachange_delta
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run in container
        run: |
          echo Running Schemachange Container
          /schemachange.sh
          
