name: Container

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-it-out:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
  my-container-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/snowflakedb/ske/ubuntu-sc:latest
      env:
        SF_ACCOUNT: account
        SF_USERNAME: user
        SF_ROLE: role
        SF_WAREHOUSE: wh
        SF_DATABASE: db
      volumes:
        - /home/runner/work/docker_test_code/docker_test_code:/github/workspace
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}
    steps:
      - name: Run in container
        run: |
          echo Running Schemachange Container
          /schemachange.sh
          
