name: 'Docker Test'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run my Docker
        uses: actions/docker_test_action
        id: docker
        with:
          command-line: 'This is my command line'
          
      - name: Get output time
        run: echo "The time was ${{ steps.docker.outputs.time }}"
